# Generated by Django 4.0.4 on 2022-05-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_patientregistrationform_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregistrationform',
            name='address_line_1',
            field=models.CharField(default='Enter your address', max_length=80),
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='address_line_2',
            field=models.CharField(default='Enter Your address', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='city',
            field=models.CharField(default='Lahore', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='contact',
            field=models.CharField(default='0320476067', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='country',
            field=models.CharField(default='PAK', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='facility',
            field=models.CharField(default='fhswf', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='language',
            field=models.CharField(default='English', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='martial_Status',
            field=models.CharField(default='Single', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='mother_First_ame',
            field=models.CharField(default='dad', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='mother_last_name',
            field=models.CharField(default='lst', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='name',
            field=models.CharField(default='Ali', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='primary_name',
            field=models.CharField(default='afdha', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='race',
            field=models.CharField(default='ada', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='reffering',
            field=models.CharField(default='asda', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='relationship',
            field=models.CharField(default='Mo', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='second_name',
            field=models.CharField(default='fdsf', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='sex',
            field=models.CharField(default='MaLe', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='specialty',
            field=models.CharField(default='dkhsadf', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='ssn',
            field=models.CharField(default='adfnaksjf', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='state',
            field=models.CharField(default='punj', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='suffix',
            field=models.CharField(default='4545', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregistrationform',
            name='zip_code',
            field=models.CharField(default='dbajfd', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientregistrationform',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patientregistrationform',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
