# Generated by Django 4.0.4 on 2022-05-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_patientregistrationform_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistrationform',
            name='address_line_2',
            field=models.CharField(default='Enter your address', max_length=50),
        ),
    ]
