# Generated by Django 4.0.4 on 2022-05-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_patientregistrationform_address_line_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregistrationform',
            name='date_of_birthday',
            field=models.CharField(default='05/09/1996', max_length=10),
            preserve_default=False,
        ),
    ]
