# Generated by Django 4.0.4 on 2022-05-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_patientregistrationform_date_of_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistrationform',
            name='date_of_birthday',
            field=models.DateField(),
        ),
    ]
